# Site settings
title: Sumit Gupta
email: me@guptasumit.com
description: > # this means to ignore newlines until "baseurl:"
  code to production and every thing in between
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://timusg.com" # the base hostname & protocol for your site
twitter_username: timusg
github_username:  timusg

analytics :
  provider : google
  google :
      tracking_id : 'UA-39717062-1'

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
